export const StudentList=[
  {
    "id": 1,
    "name": "MST SHIMA AKTER",
    "roll": 1,
    "age": 11,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2014-02-12",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 2,
    "name": "MST MUMTAHA MIMI",
    "roll": 2,
    "age": 11,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2014-03-25",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 3,
    "name": "MST MAHIA AKTER MOW",
    "roll": 3,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-11-04",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 4,
    "name": "MST JIKRA SARKER",
    "roll": 4,
    "age": 11,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2014-06-18",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 5,
    "name": "MST ROJONI AKTER ASHA",
    "roll": 5,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-12-10",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 6,
    "name": "JHUMUR RANI",
    "roll": 6,
    "age": 12,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2013-08-20",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 7,
    "name": "MST ISMOTARA KHATUN",
    "roll": 7,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-05-14",
    "section": "A",
    "admissionYear": 2022,
    "class": 6
  },
  {
    "id": 8,
    "name": "MST SUMAIYA ISLAM SONDA",
    "roll": 8,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-09-09",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 9,
    "name": "MD RAKIB HOSSAIN",
    "roll": 9,
    "age": 12,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2013-07-15",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 10,
    "name": "MD SAJIB ISLAM",
    "roll": 10,
    "age": 11,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2014-04-22",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 11,
    "name": "MD SABBIR AHMED",
    "roll": 11,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-02-28",
    "section": "B",
    "admissionYear": 2022,
    "class": 6
  },
  {
    "id": 12,
    "name": "MD RONY KHAN",
    "roll": 12,
    "age": 12,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2013-11-13",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 13,
    "name": "MD DIPTO ROY",
    "roll": 13,
    "age": 11,
    "gender": "Male",
    "religion": "Hinduism",
    "dateOfBirth": "2014-01-07",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 14,
    "name": "MD SHANTO MIA",
    "roll": 14,
    "age": 12,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2013-10-16",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 15,
    "name": "MD NAHID HOSSAIN",
    "roll": 15,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-07-30",
    "section": "B",
    "admissionYear": 2022,
    "class": 6
  },
  {
    "id": 16,
    "name": "MD MONIRUL ISLAM",
    "roll": 16,
    "age": 11,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2014-06-05",
    "section": "B",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 17,
    "name": "MST LAMIA AKTER",
    "roll": 17,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-09-03",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 18,
    "name": "MST KHUSHBU RANI",
    "roll": 18,
    "age": 12,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2013-12-21",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 19,
    "name": "MST ANIKA SULTANA",
    "roll": 19,
    "age": 11,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2014-05-11",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
  {
    "id": 20,
    "name": "MST FARHANA AKTER",
    "roll": 20,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-08-08",
    "section": "A",
    "admissionYear": 2023,
    "class": 6
  },
   {
    "id": 21,
    "name": "MD HASIBUL ISLAM",
    "roll": 1,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-03-15",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 22,
    "name": "MD ABRAR AHMED",
    "roll": 2,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-07-22",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 23,
    "name": "MST TANIA SULTANA",
    "roll": 3,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-01-09",
    "section": "A",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 24,
    "name": "MD ASIF HOSSAIN",
    "roll": 4,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-05-26",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 25,
    "name": "MST RIYA KHATUN",
    "roll": 5,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-02-14",
    "section": "A",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 26,
    "name": "MD DIPTO SAHA",
    "roll": 6,
    "age": 13,
    "gender": "Male",
    "religion": "Hinduism",
    "dateOfBirth": "2012-04-30",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 27,
    "name": "MST JANNATUL FERDOUS",
    "roll": 7,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-11-12",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 28,
    "name": "MD ARIF RAHMAN",
    "roll": 8,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-09-07",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 29,
    "name": "MST NAIMA AKTER",
    "roll": 9,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-06-18",
    "section": "B",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 30,
    "name": "MD JAWAD HOSSAIN",
    "roll": 10,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-08-03",
    "section": "B",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 31,
    "name": "MST SHARMIN SULTANA",
    "roll": 11,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-03-11",
    "section": "B",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 32,
    "name": "MD MEHEDI HASAN",
    "roll": 12,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-12-19",
    "section": "B",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 33,
    "name": "MST LIPI ROY",
    "roll": 13,
    "age": 13,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2012-07-01",
    "section": "B",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 34,
    "name": "MD ASHRAFUL ISLAM",
    "roll": 14,
    "age": 12,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2013-09-27",
    "section": "B",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 35,
    "name": "MST NOOR JAHAN",
    "roll": 15,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-10-23",
    "section": "B",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 36,
    "name": "MD SAJID ALAM",
    "roll": 16,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-06-05",
    "section": "B",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 37,
    "name": "MST MAHFUZA AKTER",
    "roll": 17,
    "age": 12,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2013-01-29",
    "section": "A",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 38,
    "name": "MST SONALI RANI",
    "roll": 18,
    "age": 13,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2012-04-16",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  {
    "id": 39,
    "name": "MD RAHAT KHAN",
    "roll": 19,
    "age": 12,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2013-05-09",
    "section": "A",
    "admissionYear": 2022,
    "class": 7
  },
  {
    "id": 40,
    "name": "MST JUI AKTER",
    "roll": 20,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-08-25",
    "section": "A",
    "admissionYear": 2021,
    "class": 7
  },
  
  {
    "id": 41,
    "name": "MD RAKIB HOSSAIN",
    "roll": 1,
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-05-12",
    "section": "A",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 42,
    "name": "MST SHIMA AKTER",
    "roll": 2,
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-06-18",
    "section": "A",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 43,
    "name": "MD ARIF RAHMAN",
    "roll": 3,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-01-22",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 44,
    "name": "MST TANIA SULTANA",
    "roll": 4,
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-09-05",
    "section": "A",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 45,
    "name": "MD ASIF HOSSAIN",
    "roll": 5,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-07-11",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 46,
    "name": "MST RIYA KHATUN",
    "roll": 6,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-03-18",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 47,
    "name": "MD MEHEDI HASAN",
    "roll": 7,
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-11-02",
    "section": "B",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 48,
    "name": "MST SHARMIN SULTANA",
    "roll": 8,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-06-29",
    "section": "B",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 49,
    "name": "MD JAWAD HOSSAIN",
    "roll": 9,
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-08-15",
    "section": "B",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 50,
    "name": "MST NAIMA AKTER",
    "roll": 10,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-05-10",
    "section": "B",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 51,
    "name": "MD ASHRAFUL ISLAM",
    "roll": 11,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-02-20",
    "section": "B",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 52,
    "name": "MST LIPI ROY",
    "roll": 12,
    "age": 13,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2012-04-05",
    "section": "B",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 53,
    "name": "MD SAJID ALAM",
    "roll": 13,
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-12-11",
    "section": "B",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 54,
    "name": "MST MAHFUZA AKTER",
    "roll": 14,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-09-30",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 55,
    "name": "MD RAHAT KHAN",
    "roll": 15,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-06-17",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 56,
    "name": "MST SONALI RANI",
    "roll": 16,
    "age": 13,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2012-08-24",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 57,
    "name": "MD ARIFUL ISLAM",
    "roll": 17,
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-10-21",
    "section": "A",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 58,
    "name": "MST JUI AKTER",
    "roll": 18,
    "age": 13,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2012-01-28",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 59,
    "name": "MD RONY KHAN",
    "roll": 19,
    "age": 13,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2012-03-16",
    "section": "A",
    "admissionYear": 2021,
    "class": 8
  },
  {
    "id": 60,
    "name": "MST SHILA PARVIN",
    "roll": 20,
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-07-04",
    "section": "B",
    "admissionYear": 2020,
    "class": 8
  },
  {
    "id": 61,
    "roll": 1,
    "name": "MD RAHIM HOSSAIN",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-05-12",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 62,
    "roll": 2,
    "name": "MST SHANTA DAS",
    "age": 15,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2010-08-22",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 63,
    "roll": 3,
    "name": "MD ARIF ALAM",
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-02-17",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 64,
    "roll": 4,
    "name": "MST LINA KHATUN",
    "age": 15,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2010-09-03",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Humanities"
  },
  {
    "id": 65,
    "roll": 5,
    "name": "MD RAFIUL ISLAM",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-12-25",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 66,
    "roll": 6,
    "name": "MST RUPA SULTANA",
    "age": 14,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2011-06-18",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 67,
    "roll": 7,
    "name": "MD ASHRAFUL HOSSAIN",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-04-11",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 68,
    "roll": 8,
    "name": "MST SUMAIYA ISLAM",
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-07-23",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Humanities"
  },
  {
    "id": 69,
    "roll": 9,
    "name": "MD RONY KHAN",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-03-15",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 70,
    "roll": 10,
    "name": "MST SHILA PARVIN",
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-08-07",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 71,
    "roll": 11,
    "name": "MD TANVIR HOSSAIN",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-11-19",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 72,
    "roll": 12,
    "name": "MST RIMI AKTER",
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-05-30",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Humanities"
  },
  {
    "id": 73,
    "roll": 13,
    "name": "MD RAKIB AHMED",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-06-08",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 74,
    "roll": 14,
    "name": "MST LINA ROY",
    "age": 15,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2010-09-21",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 75,
    "roll": 15,
    "name": "MD SAJID ALAM",
    "age": 14,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2011-02-03",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 76,
    "roll": 16,
    "name": "MST RUPA KHATUN",
    "age": 15,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2010-07-12",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Humanities"
  },
  {
    "id": 77,
    "roll": 17,
    "name": "MD ARNAB SAHA",
    "age": 14,
    "gender": "Male",
    "religion": "Hinduism",
    "dateOfBirth": "2011-01-15",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 78,
    "roll": 18,
    "name": "MST SHAHINA PARVIN",
    "age": 15,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2010-05-26",
    "section": "A",
    "admissionYear": 2023,
    "class": 9,
    "group": "Science"
  },
  {
    "id": 79,
    "roll": 19,
    "name": "MD RAHAT KHAN",
    "age": 15,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2010-03-28",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Commerce"
  },
  {
    "id": 80,
    "roll": 20,
    "name": "MST TASNIMA AKTER",
    "age": 14,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2011-09-09",
    "section": "B",
    "admissionYear": 2023,
    "class": 9,
    "group": "Humanities"
  },
  {
    "id": 81,
    "roll": 1,
    "name": "MD RAHIM HOSSAIN",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-05-12",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 82,
    "roll": 2,
    "name": "MST SHANTA DAS",
    "age": 16,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2009-08-22",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 83,
    "roll": 3,
    "name": "MD ARIF ALAM",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-02-17",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 84,
    "roll": 4,
    "name": "MST LINA KHATUN",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-09-03",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Humanities"
  },
  {
    "id": 85,
    "roll": 5,
    "name": "MD RAFIUL ISLAM",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-12-25",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 86,
    "roll": 6,
    "name": "MST RUPA SULTANA",
    "age": 16,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2009-06-18",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 87,
    "roll": 7,
    "name": "MD ASHRAFUL HOSSAIN",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-04-11",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 88,
    "roll": 8,
    "name": "MST SUMAIYA ISLAM",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-07-23",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Humanities"
  },
  {
    "id": 89,
    "roll": 9,
    "name": "MD RONY KHAN",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-03-15",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 90,
    "roll": 10,
    "name": "MST SHILA PARVIN",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-08-07",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 91,
    "roll": 11,
    "name": "MD TANVIR HOSSAIN",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-11-19",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 92,
    "roll": 12,
    "name": "MST RIMI AKTER",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-05-30",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Humanities"
  },
  {
    "id": 93,
    "roll": 13,
    "name": "MD RAKIB AHMED",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-06-08",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 94,
    "roll": 14,
    "name": "MST LINA ROY",
    "age": 16,
    "gender": "Female",
    "religion": "Hinduism",
    "dateOfBirth": "2009-09-21",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 95,
    "roll": 15,
    "name": "MD SAJID ALAM",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-02-03",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 96,
    "roll": 16,
    "name": "MST RUPA KHATUN",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-07-12",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Humanities"
  },
  {
    "id": 97,
    "roll": 17,
    "name": "MD ARNAB SAHA",
    "age": 16,
    "gender": "Male",
    "religion": "Hinduism",
    "dateOfBirth": "2009-01-15",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 98,
    "roll": 18,
    "name": "MST SHAHINA PARVIN",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-05-26",
    "section": "A",
    "admissionYear": 2022,
    "class": 10,
    "group": "Science"
  },
  {
    "id": 99,
    "roll": 19,
    "name": "MD RAHAT KHAN",
    "age": 16,
    "gender": "Male",
    "religion": "Islam",
    "dateOfBirth": "2009-03-28",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Commerce"
  },
  {
    "id": 100,
    "roll": 20,
    "name": "MST TASNIMA AKTER",
    "age": 16,
    "gender": "Female",
    "religion": "Islam",
    "dateOfBirth": "2009-09-09",
    "section": "B",
    "admissionYear": 2022,
    "class": 10,
    "group": "Humanities"
  }
]


